# Vários Perceptrons

Para classificar diferentes classes, como cachorro ou gato ou pássaro, podemos utilizar um perceptron especializado para cada classe, criando uma rede neural.

Dessa forma, dando uma entrada à rede, vemos a saída de cada neurônio, por exemplo:

- Neurônio 1, especializado em cachorro: 2
- Neurônio 2, especializado em gato: -1
- Neurônio 3, especializado em pássaro: 0.5

Como o neurônio 1 foi o mais ativado, sabemos que provavelmente o input fornecido à rede se tratava de um cachorro. Utilizando a função **Softmax**, podemos abstrair as porcentagens dando a ela as saídas da rede neural:

In [6]:
from torch import nn
import torch

softmax = nn.Softmax()

output_da_nn = torch.Tensor([2, -1, 0.5]) # variável que guardaria a saída da nn
output_ativado = softmax(output_da_nn)

print(output_ativado) # tensor([0.7856, 0.0391, 0.1753])

tensor([0.7856, 0.0391, 0.1753])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  import sys


Diferente de um perceptron normal, na qual recebe uma entrada de dimensão n e saída de dimensão 1, na rede de perceptrons temos a dimensão de saída igual a quantidade de perceptrons. 

Dessa forma, para classificar entre cachorro, gato ou pássaro, temos 3 dimensões de saída. Podemos definir essa rede de perceptrons da seguinte forma:

- n dimensões de Entrada: Coordenadas x1, x2, x3, ..., xn do espaço n-dimensional. No caso temos x1 e x2 do espaço bidimensional.
- 3 coordenadas de Saída: Quantidade de classes a serem classificadas. No caso temos cachorro, gato e pássaro.

Ou seja, 2 dimensões de entrada e 3 dimensões de saída:

In [7]:
classificador = nn.Linear(in_features = 2, out_features = 3)

Com isso, podemos pensar na dimensão de saída como sendo a quantidade de neurônios da rede. Ainda que temos vários perceptrons formando a rede, essa rede é de camada única, ou seja, todos os neurônios na mesma camada.

In [9]:
print(classificador.weight.data)
print(classificador.bias.data)

tensor([[-0.1012,  0.2469],
        [ 0.4724, -0.1613],
        [ 0.5729,  0.2040]])
tensor([-0.4865, -0.3696,  0.5208])
